# site settings
title: Reminiscence
subtitle: by Dreamer @ SFSU
email: tchiang3@mail.sfsu.edu
description: We wish to raise the empathy in disability community by using Reminiscence.
baseurl: "/reminiscence" # the subpath of your site, e.g. /blog
url: 
author:
street_address: 1600 Holloway Avenue
city: San Francisco
state: CA
zip_code: 94132
country: United States of America
phone: (415) 987-6057

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/tunni-chiang
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/tunni-chiang-9171631a3
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 


theme: "jekyll-theme-minimal"
